import React, { useState } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { Order, ProductionJob, ProductionPaper, ProductionSpecs, SiteSettings } from '../types';
import { DataService } from '../lib/dataService';

const paper = (): ProductionPaper => ({ type: '', gsm: '', source: '', parentSize: '', cutSize: '', cutQuantity: '', ups: '', sheets: '', wastage: '' });
const blankSpecs = (): ProductionSpecs => ({ deliveryDate: '', machine: '', sides: 'Single sided', frontColors: '', backColors: '', plates: '', plateSource: '', colorCheck: '', paper: [paper()], finishing: [], notes: '', finalQuantity: '', manager: '' });
const pressFields = { deliveryDate: 'Delivery date', machine: 'Printing machine / process', sides: 'Printing sides', frontColors: 'Front colors / spot inks', backColors: 'Back colors / spot inks', plates: 'Number of plates', plateSource: 'Plate source', colorCheck: 'Color check / approved by', finalQuantity: 'Final output quantity', manager: 'Production manager', notes: 'Layout, artwork, packing & production notes' };
const paperFields = { type: 'Paper / board type', gsm: 'GSM / thickness', source: 'Paper source', parentSize: 'Parent sheet size (include unit)', cutSize: 'Sheet cut size (include unit)', cutQuantity: 'Cut quantity', ups: 'Cut ups / imposition', sheets: 'Sheets to print', wastage: 'Extra / wastage sheets' };
const operations = ['Lamination', 'Foiling', 'Embossing', 'Varnish', 'Spot UV', 'Die cutting', 'Folding', 'Binding', 'Glue / pasting', 'Double-sided tape', 'Gray board', 'Rope', 'Metallic material', 'Magnet', 'Tracing', 'Ribbon', 'Tray', 'PVC plastic', 'Packing', 'Other'];
const inputClass = 'w-full border border-slate-300 rounded-lg p-2 text-sm bg-white';
const buttonClass = 'rounded-lg px-3 py-2 bg-slate-100 text-sm font-semibold disabled:opacity-50';

function Field({ label, value, onChange, required = false, type = 'text' }: { label: string; value: string; onChange: (v: string) => void; required?: boolean; type?: string }) {
  return <label className="block text-xs text-slate-600">{label}{required ? ' *' : ''}<input className={inputClass} type={type} min={type === 'number' ? 1 : undefined} required={required} value={value} onChange={e => onChange(e.target.value)} /></label>;
}

function Ticket({ job, orders, settings }: { job: ProductionJob; orders: Order[]; settings: SiteSettings }) {
  return <article><h1>{settings.documents?.companyName || 'Print Plaza'} — Production Job Order</h1><h2>{job.pjoNumber} · {job.title}</h2><p>Created: {new Date(job.createdAt).toLocaleDateString()} · Status: {job.status}</p>
    <h3>Orders in this print run</h3><table><thead><tr><th>Order / customer</th><th>Product & requirements</th><th>Quantity</th></tr></thead><tbody>{job.orderIds.map(id => {
      const order = orders.find(o => o.id === id);
      return <tr key={id}><td>{id}<br />{order?.userName || order?.userEmail}</td><td>{order?.productName || 'Order unavailable'}{order?.items?.length ? order.items.map((item, i) => <p key={i}>{item.productName} · {item.quantity} pcs</p>) : null}<p>{Object.entries(order?.finishingSpecs || {}).map(([k, v]) => `${k}: ${v}`).join('; ')}</p><p>{Object.entries(order?.options || {}).filter(([k, v]) => !/price|cost|pjo|productionJob|quotation|quoteStatus|finishing|phone|email/i.test(k) && typeof v !== 'object').map(([k, v]) => `${k}: ${v}`).join('; ')}</p></td><td>{order?.quantity}</td></tr>;
    })}</tbody></table>
    <h3>Press instructions</h3><dl>{Object.entries(pressFields).map(([key, label]) => <div key={key}><dt>{label}</dt><dd>{String(job.specs[key as keyof ProductionSpecs] || '—')}</dd></div>)}</dl>
    <h3>Paper & cutting</h3>{job.specs.paper.map((stock, i) => <section key={i}><h4>Stock {i + 1}</h4><dl>{Object.entries(paperFields).map(([key, label]) => <div key={key}><dt>{label}</dt><dd>{stock[key as keyof ProductionPaper] || '—'}</dd></div>)}</dl></section>)}
    <h3>Finishing & assembly</h3>{job.specs.finishing.length ? <table><thead><tr><th>Operation</th><th>Instructions</th><th>Quantity / source</th><th>Applies to</th><th>Sign-off</th></tr></thead><tbody>{job.specs.finishing.map((f, i) => <tr key={i}><td>{f.operation}</td><td>{f.details}</td><td>{f.quantity}<br />{f.source}</td><td>{f.orderIds.length ? f.orderIds.join(', ') : 'All orders'}</td><td>________</td></tr>)}</tbody></table> : <p>No additional finishing specified.</p>}
    <p>Pre-press approval: __________ Press operator: __________ Quality check: __________</p><p>Actual sheets: __________ Waste: __________ Final quantity: __________</p></article>;
}

function printTicket(job: ProductionJob, orders: Order[], settings: SiteSettings) {
  const popup = window.open('', '_blank');
  if (!popup) { alert('Allow pop-ups to print the PJO.'); return; }
  popup.document.write('<!doctype html><html><head><title>Production job order</title><style>body{font:12px Arial;color:#172b32;padding:24px}h1{font-size:22px}h3{border-bottom:2px solid #294d56;padding-top:12px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ccc;padding:8px;text-align:left;vertical-align:top}dl{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}dt{font-weight:bold}dd{margin:4px 0;white-space:pre-wrap;overflow-wrap:anywhere}tr,section{break-inside:avoid}@page{size:A4;margin:12mm}@media print{body{padding:0}}</style></head><body>' + renderToStaticMarkup(<Ticket job={job} orders={orders} settings={settings} />) + '</body></html>');
  popup.document.close();
  popup.focus();
  popup.print();
}

export function ProductionJobList({ jobs, orders, settings, refresh }: { jobs: ProductionJob[]; orders: Order[]; settings: SiteSettings; refresh: () => Promise<void> }) {
  const [selected, setSelected] = useState<ProductionJob | null>(null);
  const [editing, setEditing] = useState<ProductionJob | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  return <section className="bg-white border border-slate-200 rounded-xl p-4 mb-5"><h2 className="font-bold">Production job orders ({jobs.length})</h2><p className="text-xs text-slate-500 mb-3">Each PJO groups orders into one print run. Production status applies to its active orders.</p>{error && <p role="alert" className="text-red-700">{error}</p>}
    {!jobs.length && <p className="text-sm text-slate-500">No grouped PJOs yet. Select Create PJO to plan your first run.</p>}
    <div className="space-y-2">{jobs.map(job => <div key={job.id} className="flex flex-wrap gap-3 items-center border rounded-lg p-3"><div className="flex-1"><strong>{job.pjoNumber} · {job.title}</strong><p className="text-xs text-slate-500">{job.orderIds.length} order(s) · {job.specs.paper.map(p => `${p.type} ${p.gsm} ${p.cutSize}`).join(' / ')}</p></div><select aria-label={`Status of ${job.pjoNumber}`} className="border rounded-lg p-2 text-sm" value={job.status} disabled={busy} onChange={async e => { setBusy(true); setError(''); try { await DataService.updateProductionJob(job.id, e.target.value as ProductionJob['status']); await refresh(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to update PJO.'); } finally { setBusy(false); } }}><option value="pending">Planned</option><option value="processing">In production</option><option value="completed">Completed</option></select><button className={buttonClass} onClick={() => setSelected(job)}>View ticket</button>{job.status !== 'completed' && <button className={buttonClass} onClick={() => setEditing(job)}>Edit specs</button>}<button className={buttonClass} onClick={() => printTicket(job, orders, settings)}>Print PJO</button></div>)}</div>
    {editing && <CreateProductionJob existing={editing} orders={orders} onClose={() => setEditing(null)} onSaved={refresh} />}
    {selected && <div className="fixed inset-0 bg-black/50 z-50 p-5 overflow-y-auto"><div className="bg-white max-w-5xl mx-auto p-6 rounded-xl"><div className="flex justify-end gap-2"><button className={buttonClass} onClick={() => printTicket(selected, orders, settings)}>Print</button><button className={buttonClass} onClick={() => setSelected(null)}>Close</button></div><div className="[&_h1]:text-xl [&_h2]:font-bold [&_h3]:font-bold [&_h3]:mt-5 [&_table]:w-full [&_td]:border [&_td]:p-2 [&_th]:text-left [&_dl]:grid [&_dl]:grid-cols-3 [&_dl]:gap-3 [&_dt]:text-xs [&_dd]:whitespace-pre-wrap"><Ticket job={selected} orders={orders} settings={settings} /></div></div></div>}
  </section>;
}

export function CreateProductionJob({ orders, onClose, onSaved, existing }: { orders: Order[]; onClose: () => void; onSaved: () => Promise<void>; existing?: ProductionJob }) {
  const [title, setTitle] = useState(existing?.title || '');
  const [query, setQuery] = useState('');
  const [ids, setIds] = useState<string[]>(existing?.orderIds || []);
  const [specs, setSpecs] = useState<ProductionSpecs>(() => existing?.specs || blankSpecs());
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const eligible = orders.filter(o => existing ? existing.orderIds.includes(o.id) : !o.isQuotation && o.status === 'pending' && !o.pjoNumber);
  const visible = eligible.filter(o => `${o.id} ${o.productName} ${o.userName} ${o.userEmail}`.toLowerCase().includes(query.toLowerCase()));
  const changeStock = (i: number, key: keyof ProductionPaper, value: string) => setSpecs(s => ({ ...s, paper: s.paper.map((p, index) => index === i ? { ...p, [key]: value } : p) }));
  return <div className="fixed inset-0 z-50 bg-slate-900/60 p-4 flex justify-center"><form className="bg-white rounded-2xl w-full max-w-6xl flex flex-col overflow-hidden" onSubmit={async e => { e.preventDefault(); if (!ids.length) { setError('Select at least one waiting order.'); return; } setBusy(true); setError(''); try { if (existing) await DataService.saveProductionSpecs(existing.id, { title, orderIds: ids, specs }); else await DataService.createProductionJob({ title, orderIds: ids, specs }); await onSaved(); onClose(); } catch (err) { setError(err instanceof Error ? err.message : 'Could not create PJO.'); } finally { setBusy(false); } }}>
    <header className="p-5 border-b flex justify-between"><div><h2 className="text-lg font-bold">{existing ? `Edit ${existing.pjoNumber}` : 'Create production job order'}</h2><p className="text-sm text-slate-500">Combine compatible orders into one print run.</p></div><button type="button" disabled={busy} onClick={onClose}>Close</button></header>
    <div className="overflow-y-auto p-5 space-y-6"><Field label="PJO name" value={title} onChange={setTitle} required />
      <section><h3 className="font-bold mb-2">1. Select orders · {ids.length} selected</h3><input aria-label="Search waiting orders" placeholder="Search by product, customer or order number" className={inputClass} value={query} onChange={e => setQuery(e.target.value)} /><p className="text-xs text-slate-500 my-2">Check paper, colors and finishing requirements before grouping. Each order can belong to one PJO.</p><div className="max-h-64 overflow-y-auto border rounded-lg">{visible.map(o => <label key={o.id} className="flex gap-3 p-3 border-b items-start"><input type="checkbox" disabled={!!existing} checked={ids.includes(o.id)} onChange={e => { setIds(e.target.checked ? [...ids, o.id] : ids.filter(id => id !== o.id)); if (!e.target.checked) setSpecs(s => ({ ...s, finishing: s.finishing.map(f => ({ ...f, orderIds: f.orderIds.filter(id => id !== o.id) })) })); }} /><div className="text-sm"><strong>{o.productName} · {o.quantity.toLocaleString()} pcs</strong><p>{o.userName || o.userEmail} · {o.id}</p><p className="text-xs text-slate-500">{Object.entries(o.finishingSpecs || {}).map(([k, v]) => `${k}: ${v}`).join(' · ')}</p><p className="text-xs text-slate-500">{Object.entries(o.options || {}).filter(([k, v]) => !/price|cost|quote|finishing/i.test(k) && typeof v !== 'object').map(([k, v]) => `${k}: ${v}`).join(' · ')}</p></div></label>)}{!visible.length && <p className="p-4 text-sm text-slate-500">No waiting orders found. Confirm a quotation or add a customer order first.</p>}</div></section>
      <section><h3 className="font-bold mb-3">2. Paper & sheet cutting</h3>{specs.paper.map((stock, i) => <div key={i} className="border rounded-xl p-4 mb-3"><div className="flex justify-between mb-2"><h4 className="font-semibold">Stock {i + 1}</h4>{specs.paper.length > 1 && <button type="button" onClick={() => setSpecs(s => ({ ...s, paper: s.paper.filter((_, n) => n !== i) }))}>Remove stock</button>}</div><div className="grid grid-cols-2 md:grid-cols-3 gap-3">{Object.entries(paperFields).map(([key, label]) => <Field key={key} label={label} value={stock[key as keyof ProductionPaper]} onChange={v => changeStock(i, key as keyof ProductionPaper, v)} required={['type', 'cutSize', 'sheets'].includes(key)} type={key === 'sheets' ? 'number' : 'text'} />)}</div></div>)}<button type="button" className={buttonClass} onClick={() => setSpecs(s => ({ ...s, paper: [...s.paper, paper()] }))}>+ Add paper / board stock</button></section>
      <section><h3 className="font-bold mb-3">3. Printing & delivery</h3><div className="grid grid-cols-2 md:grid-cols-3 gap-3">{Object.entries(pressFields).filter(([k]) => k !== 'notes').map(([key, label]) => <Field key={key} label={label} value={String(specs[key as keyof ProductionSpecs])} type={key === 'deliveryDate' ? 'date' : 'text'} onChange={v => setSpecs(s => ({ ...s, [key]: v }))} />)}</div></section>
      <section><h3 className="font-bold mb-2">4. Finishing & assembly</h3><p className="text-xs text-slate-500 mb-3">Specify type, size, front/back, color and any special instructions. Apply an operation to all orders or selected orders.</p>{specs.finishing.map((f, i) => {
        const update = (value: Partial<typeof f>) => setSpecs(s => ({ ...s, finishing: s.finishing.map((v, n) => n === i ? { ...v, ...value } : v) }));
        return <div key={i} className="border rounded-xl p-4 mb-3 space-y-3"><div className="flex gap-3"><select aria-label="Finishing operation" className={inputClass} value={f.operation} onChange={e => update({ operation: e.target.value })}>{operations.map(o => <option key={o}>{o}</option>)}</select><button type="button" onClick={() => setSpecs(s => ({ ...s, finishing: s.finishing.filter((_, n) => n !== i) }))}>Remove</button></div><Field label="Type / color / sides / size / instructions" required value={f.details} onChange={details => update({ details })} /><div className="grid grid-cols-2 gap-3"><Field label="Quantity" value={f.quantity} onChange={quantity => update({ quantity })} /><Field label="Source / supplier" value={f.source} onChange={source => update({ source })} /></div><label className="text-xs block">Applies to (leave unselected for all orders)<select multiple className={inputClass} value={f.orderIds} onChange={e => update({ orderIds: Array.from(e.target.selectedOptions, o => o.value) })}>{orders.filter(o => ids.includes(o.id)).map(o => <option key={o.id} value={o.id}>{o.productName} · {o.userName || o.userEmail} · {o.id}</option>)}</select></label></div>;
      })}<button type="button" className={buttonClass} onClick={() => setSpecs(s => ({ ...s, finishing: [...s.finishing, { operation: 'Lamination', details: '', quantity: '', source: '', orderIds: [] }] }))}>+ Add finishing operation</button></section>
      <label className="block text-sm">Layout, artwork, packing & production notes<textarea className={inputClass} rows={4} value={specs.notes} onChange={e => setSpecs(s => ({ ...s, notes: e.target.value }))} /></label>
    </div><footer className="border-t p-4 flex items-center justify-between gap-4">{error ? <p role="alert" className="text-sm text-red-700">{error}</p> : <p className="text-sm text-slate-500">{ids.length} order(s) selected · Customer invoices stay separate.</p>}<button disabled={busy || !ids.length} className="bg-[#2D545E] text-white rounded-lg px-5 py-2 disabled:opacity-50 shrink-0">{busy ? 'Saving…' : existing ? 'Save specifications' : 'Create PJO'}</button></footer>
  </form></div>;
}
